### ISSUE TITLE
Plus sign literals in argument to `derive` always give an empty charclass

### ISSUE THREAD

**Issue by lmmx** [qntm/greenery#104]
I was processing regexes with various parts of greenery and believe I've found a bug in `derive`'s handling of `r"\+"`.

## Not previously documented, so presume to be a bug

I've read the docs and see no mention besides the following:

> The following metacharacters and formations have their usual meanings: `.`, `*`, `+`, `?`, `{m}`, `{m,}`, `{m,n}`, `()`, `|`, `[]`, `^` within `[]` character ranges only, `-` within `[]` character ranges only, and `\` to escape any of the preceding characters or itself.

I take this to mean that `should be used to escape the `+` character (as is conventional, and not surprising).

## Expected behaviour

There are tests demonstrating how `derive` works in the `rxelems_test.py` module

https://github.com/qntm/greenery/blob/10223e69236f04ee6fd9dfe99262046f0333bda1/greenery/rxelems_test.py#L882-L887

These respectively show that:

1. `a+` (1 or more `a`), `derive`'d by `a`, gives `a*` (0 or more `a`)
2. `a+` (1 or more `a`) _or_ `b+` (1 or more `b`), `derive`'d by `a`, gives `a*` (0 or more `a`)
3. `abc` _or_ `ade`, `derive`'d by `a`, gives `bc` _or_ `de`
4. `abc` _or_ `ade`, `derive`'d by `ab`, gives `c`
5. `abc` _or_ `ade`, `derive`'d by `c`, gives `[]` (the empty character class)

From the README:

> An empty charclass `[]` is legal and matches no characters: when used in a regular expression, the regular expression may match no strings.

## Unexpected behaviour with `r"\+"`

The plus sign handling should work like this (checked items are those which _do_ behave like this):

- [x] `r"a\+".derive("a")` should give `r"\+"`
- [x] `r"ab\+c".derive("ab")` should give `r"\+c"`

```py
>>> str(parse(r"a\+").derive(r"a"))
'\\+'
>>> str(parse(r"ab\+c").derive(r"ab"))
'\\+c'
```

- [ ] `r"a\+b"` derived by `r"a\+"` should give `"b"`
- [ ] `r"ab\+c"` derived by `r"ab\+"` should give `"c"`

```py
>>> str(parse(r"a\+b").derive(r"a\+"))
'[]'
>>> str(parse(r"ab\+c").derive(r"ab\+"))
'[]'
```

These instead give an empty charclass `[]`, which I think is incorrect.

It appears in cases where the `r"\+"` sign is in the right hand pattern (i.e. the argument to `derive`).

I haven't currently located it any further than this but will update this issue if I do.

**Comment by qntm** [comment]
My guess is that this could be to do with your use of backslashes. Remember the input to the Brzozowski derivative is a plain old string, not a regular expression - as such, it does not need special characters to be escaped in any way. So try `parse(r"a\+b").derive("a+")`.

**Comment by lmmx** [comment]
Oh! Thank you @qntm I hadn't picked up on that :-)
