### ISSUE TITLE
Support for lazy quantifiers

### ISSUE THREAD

**Issue by michaelmior** [qntm/greenery#107]
Greenery doesn't seem to support lazy quantifiers, for example `o{0,1}?`. Currently I run into a parser error.

```
>>> greenery.parse('o{0,1}?')
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.2.1) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mmior/.local/lib/python3.8/site-packages/greenery/parse.py", line 371, in parse
    raise NoMatch(f"Could not parse {string!r} beyond index {i}")
greenery.parse.NoMatch: Could not parse 'o{0,1}?' beyond index 6
```

**Comment by michaelmior** [comment]
@qntm Got it, thanks for the response. I guess that means it doesn't support lazy/greedy modifiers at all, which makes sense. Although I will say that it would be very helpful for my use case if the parser would accept such regexes anyway. I'm dealing with a scenario where I'd like to be able to handle as broad a set of expressions as possible.

While of course I could find a way to parse the expression using some other method and remove lazy and greedy modifiers before feeding to greenery, it would be nice to be able to skip this step.

**Comment by qntm** [comment]
There is a small amount of precedent for allowing syntax in the parser even though it doesn't make a material difference. I will consider this.

**Comment by michaelmior** [comment]
@qntm Thanks! I appreciate it :)

**Comment by michaelmior** [comment]
Also, I apologize that I missed that lack of support for lazy/greedy modifiers is explicitly mentioned in the README…

**Comment by qntm** [comment]
Give `greenery-4.2.1` a try.

**Comment by michaelmior** [comment]
@qntm Works great! Thanks :)
