### ISSUE TITLE
fsm.union() with no args fails, on Python 2; causes failing test case in fsm_test.py

### ISSUE THREAD

**Issue by davidwagner** [qntm/greenery#33]
Calling `fsm.union()` with no arguments fails on Python 2.7:

    >>> from greenery.fsm import fsm
    >>> fsm.union()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: unbound method union() must be called with fsm instance as first argument (got nothing instead)   

The method documentation makes it sound like it should succeed.  This succeeds on Python 3.5.

This causes one of the test cases in `fsm_test.py` to fail, on Python 2.7:

        def test_new_set_methods(a, b):
    >   	assert len(fsm.union()) == 0
    E    TypeError: unbound method union() must be called with fsm instance as first argument (got nothing instead)

In contrast, all tests pass for `fsm_test.py` on Python 3.5.  I'm using version 3.0 of the greenery library, as installed via Pip.

**Comment by qntm** [comment]
Same response as for #32: I'm sorry, but unfortunately Python 2.x is not supported. I will rectify the README to signal this now.

**Comment by qntm** [comment]
[README updated](https://github.com/qntm/greenery/commit/2fb70ce9b17e1522b7c324c87847d3a5ed2ceeeb).

**Comment by pjkundert** [comment]
Just FYI, the greenery versions available via pip between 2.0 and 3.0 are fully functional in both Python 2.x and 3.x.  I've used the extensively in the python 'cpppo' project , and they are quite stable and useful.
