### ISSUE TITLE
Multiple tests fail for lego_test.py, on Python 2

### ISSUE THREAD

**Issue by davidwagner** [qntm/greenery#34]
On Python 2.7, 24 of the 95 tests in `lego_test.py` fail.  This includes:

- Infinite recursion for `test_binary_3`, `test_base_N`, `test_everythingbut`, `test_isinstance_bug`, and others (maybe related to issue #32 ?)
- Assertion failures for `test_conc_common`, `test_pattern_commonconc`, `test_pattern_commonconc_suffix`, `test_conc_dock`, and others
- Exception raised for `test_mult_doc` and others

On Python 3.5, all the tests pass.  I'm using greenery version 3.0, as installed by Pip.

**Comment by qntm** [comment]
Same response as for #32: I'm sorry, but unfortunately Python 2.x is not supported. I will rectify the README to signal this now.

**Comment by qntm** [comment]
[README updated](https://github.com/qntm/greenery/commit/2fb70ce9b17e1522b7c324c87847d3a5ed2ceeeb).
