### ISSUE TITLE
deepcopy changes finite state machine

### ISSUE THREAD

**Issue by hgao10** [qntm/greenery#41]
I am trying to use the finite state machines and regex together in my code but the finite state machine changes when I copy the object
```python
regex = parse(".*")
fsm = regex.to_fsm()
fsm_copy = copy.deepcopy(fsm)
fsm.equivalent(regex.to_fsm())  # True
fsm_copy.equivalent(regex.to_fsm()) # False
fsm_copy.equivalent(fsm) # False
```

**Comment by qntm** [comment]
`fsm` objects are intended to be immutable, so it should never be necessary to copy them in this way. Is there a reason you're not able to do

```python
fsm_copy = fsm
```

?
