### ISSUE TITLE
Regexp standard .posix or w3c?

### ISSUE THREAD

**Issue by faraazc** [qntm/greenery#42]
I want to know the format and standard of regex this tool is complaint with..thanks.

Whether it's w3c based or posix based?

**Comment by qntm** [comment]
I don't know what you mean by a W3C-based regular expression.

See [here in the README](https://github.com/qntm/greenery#legoparsestring) for a list of supported constructs. You will find that this is a fairly narrow subset of POSIX-based regular expressions.
