### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by andrewhabib** [qntm/greenery#46]
Hi,

Thanks for a great project! 

I was inquiring why we haven't seen a new release on pypi since ver. 3.1 on April 2018?
greenery went through several improvements/bug fixes over the past period and it would be very useful if a new release is available on pypi... especially for libraries which directly depend on greenery (like our https://github.com/IBM/jsonsubschema) library. 

Is there anything we can help with to speed up this?

Regards,

**Comment by qntm** [comment]
As you can imagine it's been more than two years since I last fooled around with the Python packaging ecosystem so I may have got this dead wrong, but [try this](https://pypi.org/project/greenery/3.2/).

**Comment by andrewhabib** [comment]
Thanks a lot! 
I can confirm that the new release works perfectly. 
Will close the issue.
