### ISSUE TITLE
Greenery fails to output meaningful regex for particular FSM

### ISSUE THREAD

**Issue by dk2k** [qntm/greenery#48]
My sample python file:

from greenery import fsm, lego

S5, S26, S45, S63, S80, S97, S113, S127, S140, S152, S163, S175, S182 = range(13)
char0, char1, char2, char3, char4, char5, char6, char7, char8 = '_', 'a', 'd', 'e', 'g', 'm', 'n', 'o', 'p'

machine = fsm.fsm(
        alphabet = { char0, char1, char2, char3, char4, char5, char6, char7, char8 },
        states = {S5, S26, S45, S63, S80, S97, S113, S127, S140, S152, S163, S175, S182 },

        initial = S5,
        finals = {S182},
        map = {
                        S113: {char0: S127},
                        S127: {char7: S140},
                        S140: {char6: S152},
                        S152: {char0: S163},
                        S163: {char5: S175},
                        S175: {char8: S182},
                        S26: {char1: S45},
                        S45: {char5: S63},
                        S5: {char2: S26},
                        S63: {char1: S80},
                        S80: {char4: S97},
                        S97: {char3: S113},
        },
)

rex = lego.from_fsm(machine)
print(rex)

print(machine)

---------------------
No errors reported and the output is:

[]
  name final? _  a d e g m  n o p
-----------------------------------
* 0    False       1
  1    False     2
  2    False             3
  3    False     4
  4    False           5
  5    False         6
  6    False  7
  7    False                  8
  8    False                9
  9    False  10
  10   False             11
  11   False                    12
  12   True

What am I supposed to change in the python file to see regex  damage_on_mp ?

**Comment by qntm** [comment]
Should be fixed in [`greenery-3.3.1`](https://pypi.org/manage/project/greenery/release/3.3.1/).
