### ISSUE TITLE
Suggesting a unit test

### ISSUE THREAD

**Issue by dk2k** [qntm/greenery#50]
Hi! Thanks for quick reaction on the issue #48 yesterday.
I have another real life FSM, just want to share for unit test.
Just in case: the actual version processes it just fine.
Most likely I will have more examples. If you are interested, contact me krjukov@gmail.com

from greenery import fsm, lego

S40, S59 = range(2)
char0, char1, char10, char2, char3, char4, char5, char6, char7, char8, char9 = '0', '1', '.', '2', '3', '4', '5', '6', '7', '8', '9'

machine = fsm.fsm(
        alphabet = { char0, char1, char10, char2, char3, char4, char5, char6, char7, char8, char9 },
        states = {S40, S59},

        initial = S59,
        finals = {S40},
        map = {
             S40: {char7: S40, char3: S40, char4: S40, char0: S40, char8: S40, char5: S40, char1: S40, char9: S40, char6: S40, char2: S40},
             S59: {char7: S59, char3: S59, char10: S40, char4: S59, char0: S59, char8: S59, char5: S59, char1: S59, char9: S59, char6: S59, char2: S59},
        },
)

rex = lego.from_fsm(machine)
print(rex)

Outputs as expected: \d*\\.\d*

**Comment by qntm** [comment]
If you run into more bugs I will be happy to add regression tests, or if you can show that your test case exercises behaviour which all the other unit tests don't cover. Other than that, I'm less worried.

**Comment by dk2k** [comment]
I though there maybe some value in the fact that alphabet isn't sorted as well as the transitions in the map section. State names aren't canonical A, B, ... If it's not the case, please discard it.
