### ISSUE TITLE
Character | is left unescaped

### ISSUE THREAD

**Issue by dk2k** [qntm/greenery#51]
Sample script:

from greenery import fsm, lego

S1, S5 = range(2)
char0, char1, char2 = '\n', '\r', '|'

machine = fsm.fsm(
	alphabet = { char0, char1, char2 }, 
	states = {S1, S5	}, 

	initial = S1,
	finals = {S5},
	map = {
			S1: {char2: S5, char1: S5, char0: S5},
	}, 
) 

rex = lego.from_fsm(machine)
print(rex)

Currently output is [\n\r|]
I assume it should be [\n\r\|] as it becomes [\n\r\[] when I substitute | to [

**Comment by qntm** [comment]
You're saying it outputs `[\n\r|]` when in fact it should output `[\n\r\|]`? I think that's actually the correct behaviour. In the context of a character class (that is, between a `[` and a `]`), the pipe character has no special meaning. It does not require escaping in that context.

I suppose a case can be made that a `[` also has no special meaning in that context, so it outputs `[\n\r\[]` when in fact it should output `[\n\r[]`. You may be right about that, although personally I find the latter a little confusing and potentially ambiguous. I will think about this.

**Comment by qntm** [comment]
I am of the opinion that outputting `[\n\r\[]` is not incorrect behaviour or confusing behaviour. In fact I consider it marginally more legible and unambiguous. I also consider it marginally more consistent, as `]` *does* have to be escaped.
