### ISSUE TITLE
Do not instantiate character ranges?

### ISSUE THREAD

**Issue by mristin** [qntm/greenery#81]
Thank you a lot for this really nice library!

We are trying to merge a couple of patterns, where one pattern consists of a series of character ranges. Namely, we look into characters permitted by XML 1.0:

```
import greenery

greenery.parse('^[\t\n\r -\uD7FF\uE000-\uFFFD\U00010000-\U0010FFFF]*$')
```

We noticed that greenery immediately instantiates the character ranges into individual characters. Merging this pattern with any other pattern becomes obviously intractable on personal computers.

Have you ever considered handling of character ranges in a special manner rather than instantiating them immediately?

**Comment by qntm** [comment]
I have considered this scenario before, but no one has ever actually asked for this up until now. I will look into this at some point but I cannot provide a timeframe. This has a potential to be either doable or very intractable, I won't know until I set some time aside to take a closer look.

**Comment by mristin** [comment]
@qntm thanks! 

This is a quite common scenario in automation field, which still relies heavily on XML and no chaining of patterns in XSD is possible.

**Comment by MegaIng** [comment]
I actually just implemented something like going into this direction in my semi-fork https://github.com/MegaIng/interegular

@qntm If you haven't started with this, I would give it a try.

My idea is to basically have an `Alphabet` class that translates external symbols (i.e. individual chars) into `TransitionKeys` that are used inside the FSM instances. (basically something you suggested a few years ago to me). While I didn't implement it condensing ranges (I still have all characters in the range individually in the Alphabet), that shouldn't be that hard of an extra step I think.

**Comment by qntm** [comment]
@mristin @MegaIng I have made the suggested internal changes. Give `greenery-4.1.0` a whirl. I think I knocked out the major performance quandaries, but I would be interested to know how this works now, particularly if you're able to give examples of operations which are still taking excessive amounts of time.

**Comment by mristin** [comment]
@qntm thanks for the change! I expect to test it these days, hopefully tonight.

Sorry for the late response.

**Comment by mristin** [comment]
Here is one test case if you want to include it in your test suite:
https://github.com/admin-shell-io/aas-specs/blob/2fe82a66ca502f9c5aea1ef0de0baaa729469faf/schemas/json/aas.json#L67

The two patterns should be merged into one.

**Comment by mristin** [comment]
@qntm works like a charm! I have to do more testing, but for now I'd like to confirm:

```python
import greenery

r1 = greenery.parse('^[\t\n\r -\uD7FF\uE000-\uFFFD\U00010000-\U0010FFFF]*$')
r2 = greenery.parse("^(0|[1-9][0-9]*)$")

print(r1 & r2)
```

... outputs:

```
^(0|[1-9]\d*)$
```

This is great, thanks!

**Comment by mristin** [comment]
Since it all seems to work on my side, I'll close the issue.

**Comment by mristin** [comment]
@qntm thanks again for the change!
