### ISSUE TITLE
`pip install` command recommended in README doesn't work

### ISSUE THREAD

**Issue by qntm** [qntm/greenery#92]
```
$ pip install -r requirements.dev.txt
Collecting black
  Using cached black-23.1.0-py3-none-any.whl (174 kB)
ERROR: Cannot install flake8 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested flake8
    The user requested (constraint) flake8==6.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

I'll be honest: I do not comprehend how this could possibly constitute a dependency conflict. It seems like `flake8` with no version specifier is perfectly reconcilable with `flake8==6.0.0`. @rwe

**Comment by rwe** [comment]
That's unexpected, and I'm having trouble replicating in a clean virtualenv in either python 3.8.10 or 3.11.1; pip 21 or pip 23.

Can you share output of `pip --version`? You might want to try `pip install --upgrade pip`; if it's a super old installation, it might cause problems. That said, I would not have expected an error like that a few years ago either, so it's possible I'm overlooking something.

**Comment by qntm** [comment]
```
$ pip --version
pip 23.0.1 from C:\Users\qntm\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip (python 3.8)
```

**Comment by qntm** [comment]
OK so revisiting this today I came to the suspicion that my local Python environment was just broken. I deleted my Python installation and tried again, using [`pyenv`](https://github.com/pyenv-win/pyenv-win) this time, and it seems to have worked. I'm now seeing issues with `mypy greenery` and ``pytest` but this issue is done.
